### ISSUE TITLE
Add artifact summary

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/qiime2#342] opened 2017-09-29 19:35 UTC
It would be nice to be able to inspect an artifact from the command line, think of something similar to what was possible with `biom summarize-table` but generalized to any Artifact. For example `qiime tools peek` could produce this information:

```
(qiime2-2017.9) yovazquezbaeza:redacted$ qiime tools peek redacted/feature-table.qza
UUID:        1d4488e2-c62c-4df0-82c2-98e098ed4aea
Type:        FeatureTable[Frequency]
Data format: BIOMV210DirFmt
Summary:
Number of samples: 11
Number of features: 11,111
... other stats ...
```

Or alternatively:
```
(qiime2-2017.9) yovazquezbaeza:redacted$ qiime tools peek redacted/pcoa-results.qza
UUID:        1d4488e2-c62c-4df0-82c2-98e098ed4aea
Type:        PCoAResults
Data format: OrdinationDirectoryFormat
Summary:
Number of samples: 11
```

**Comment by jairideout** [comment] 2017-09-30 03:14
Duplicate of #197

**Closed by jairideout** 2017-09-30 03:14 UTC

**Comment by ElDeveloper** [comment] 2017-09-30 03:50
🏖 🍻
