### ISSUE TITLE
Add type validation to Metadata[Category] creation

### ISSUE THREAD

**Issue by jakereps** [qiime2/qiime2#313] opened 2017-08-03 19:25 UTC
Currently `Metadata` and `MetadataCategory` take in a `pd.DataFrame` and `pd.Series` respectively. However, there is no validation that the correct data type is being passed in, which is causing strange errors downstream.

Example: 
Demultiplexing with a `MetadataCategory` that was incorrectly passed a 1 column DataFrame, (`pd.read_csv`'s default return type, regardless of the number of columns), there were no errors presented at the time, so when it went into `emp_single` way down the stack it erred inside of `skbio` with an unhelpful error message about needing a bytes-like object, but instead received a Series, because calling for the sample id within a DataFrame returns a `pd.Series` object of the entire row, even though there is only one column, instead of just the value it expected (the barcode).

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-113-647390b0f86d> in <module>()
      1 seqs = Artifact.load('/home/seq_run_pipeline/20170622_1/seqs.qza')
      2 barcodes = MetadataCategory(df)
----> 3 emp_single(seqs, barcodes, rev_comp_barcodes=True, rev_comp_mapping_barcodes=True)

<decorator-gen-256> in emp_single(seqs, barcodes, rev_comp_barcodes, rev_comp_mapping_barcodes)

~/dev/mc3/envs/biota/lib/python3.5/site-packages/qiime2/sdk/action.py in callable_wrapper(*args, **kwargs)
    198 
    199             outputs = self._callable_executor_(self._callable, view_args,
--> 200                                                output_types, provenance)
    201             # The outputs don't need to be orphaned, because their destructors
    202             # aren't invoked in atexit for a subprocess, instead the

~/dev/mc3/envs/biota/lib/python3.5/site-packages/qiime2/sdk/action.py in _callable_executor_(self, callable, view_args, output_types, provenance)
    277                             provenance):
    278         is_subprocess = self._is_subprocess()
--> 279         output_views = callable(**view_args)
    280         output_views = tuplize(output_views)
    281 

~/dev/mc3/envs/biota/lib/python3.5/site-packages/q2_demux/_demux.py in emp_single(seqs, barcodes, rev_comp_barcodes, rev_comp_mapping_barcodes)
    249     result = SingleLanePerSampleSingleEndFastqDirFmt()
    250     barcode_map, barcode_len = _make_barcode_map(
--> 251         barcodes, rev_comp_mapping_barcodes)
    252 
    253     manifest = FastqManifestFormat()

~/dev/mc3/envs/biota/lib/python3.5/site-packages/q2_demux/_demux.py in _make_barcode_map(barcodes, rev_comp_mapping_barcodes)
    225                              'supported.' % (len(barcode), barcode_len))
    226         if rev_comp_mapping_barcodes:
--> 227             barcode = str(skbio.DNA(barcode).reverse_complement())
    228         if barcode in barcode_map:
    229             raise ValueError('A duplicate barcode was detected. The barcode '

~/dev/mc3/envs/biota/lib/python3.5/site-packages/skbio/sequence/_grammared_sequence.py in __init__(self, sequence, metadata, positional_metadata, interval_metadata, lowercase, validate)
    333         super(GrammaredSequence, self).__init__(
    334             sequence, metadata, positional_metadata,
--> 335             interval_metadata, lowercase)
    336 
    337         if validate:

~/dev/mc3/envs/biota/lib/python3.5/site-packages/skbio/sequence/_sequence.py in __init__(self, sequence, metadata, positional_metadata, interval_metadata, lowercase)
    629             if isinstance(sequence, str):
    630                 sequence = sequence.encode("ascii")
--> 631             s = np.fromstring(sequence, dtype=np.uint8)
    632 
    633             # There are two possibilities (to our knowledge) at this point:

TypeError: a bytes-like object is required, not 'Series'
```

**Comment by jairideout** [comment] 2017-08-06 14:55
Related to, or possible duplicate of, https://github.com/qiime2/qiime2/issues/298

**Comment by jakereps** [comment] 2017-08-06 22:10
I don't think it's related to that issue, as that seems to be referring more to the actual internals of the DataFrame/Series. This is just that [there is no validation that MC is actually being passed a Series](https://github.com/qiime2/qiime2/blob/master/qiime2/metadata.py#L275).

**Comment by jairideout** [comment] 2017-08-07 14:41
Oh I see now, it's validation one level higher (checking container type instead of contents). Thanks @jakereps!

**Closed** 2017-08-23 22:51 UTC
Labels: bug
