### ISSUE TITLE
Current dev conda environment file is broken for MacOS 

### ISSUE THREAD

**Issue by cdiener** [qiime2/qiime2#535] opened 2020-04-20 16:27 UTC
**Bug Description**

The current dev version can not be installed on MacOS due to a broken package in the conda environment YML. 

**Steps to reproduce the behavior**

Follow the instructions from https://dev.qiime2.org/latest/quickstart/ on MacOS:

```bash
wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-osx-conda.yml
conda env create -n qiime2-dev --file qiime2-latest-py36-osx-conda.yml
rm qiime2-latest-py36-osx-conda.yml
```

**Expected behavior**

Installation should finish successfully but will raise an error.

```bash
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - libcxx=10.0.0
```

**Screenshots**

See https://dev.azure.com/chdiener/cdiener/_build/results?buildId=89&view=logs&j=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f&t=4dcf5c97-b0e1-5f3b-ee15-0b0e2a3ffb0c for a full CI run.

**Computation Environment**
- Azure pipelines `macOS-latest` image.

**Questions**
None.

**Comments**
This is due to the package `libcxx` which is requested as version 10.0.0 on mac but this version has been labeled broken on conda-forge and can thus not be installed:
https://anaconda.org/conda-forge/libcxx/files

**Comment by andrewsanchez** [comment] 2020-04-20 20:04
Hi, @cdiener!  Thanks for the report.

Some notes:

- I was able to reproduce locally today
  - I thought this odd, because I definitely installed a fresh dev environment using using the env file _after_ `libcxx` was pinned to 10.0.0 in `latest/staging/qiime2-latest-py36-osx-conda.yml` without problems
  - The only difference I can think of is that I had uninstalled/re-installed the command line developer tools, i.e. `rm -r /Library/Developer/CommandLineTools && xcode-select --install`

**Potentially related**

- Xcode updates for an Azure pipeline mac os image in this PR https://github.com/microsoft/azure-pipelines-image-generation/pull/1511

**Successful mac os builds with `libcxx==10.0.0`**

 - https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/integration/builds/192
- on my machine, prior to re-installing the command line developer tools

**Related issues and PRs**
- https://github.com/conda-forge/libcxx-feedstock/issues?q=is%3Aopen

It seems to me that we should keep an eye on conda-forge/libcxx-feedstock to see if the problem is resolved before spending any more time investigating.

[This thread](https://github.com/actions/virtual-environments/issues/620#issuecomment-613313986) has some Azure specific discussion which might be useful in the meantime, @cdiener .

**Comment by cdiener** [comment] 2020-04-20 20:10
I don't think it Azure-related. On my local machine I can trigger the issue with a simple

```bash
conda install -c conda-forge "libcxx==10.0.0"
```

**Comment by thermokarst** [comment] 2020-04-20 20:22
Thanks @cdiener, I agree w your assessment. This should be resolved next time busywork.qiime2.org kicks off another integration build - it'll pick up a different build or version of the offending packages. Closing now, but reopen if it's still a problem in a few days. Thanks!

**Closed by thermokarst** 2020-04-20 20:22 UTC

**Comment by thermokarst** [comment] 2020-04-21 18:18
A new integration [build is cooking](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/integration/builds/193) - looks like libcxx 9 was pulled in from conda-forge. I'll try to update this issue once the new staging env file is cut.

**Comment by thermokarst** [comment] 2020-04-21 20:49
@cdiener - a new staging env is up, here is the diff:

https://github.com/qiime2/environment-files/commit/9bb6b2bab6f037bf4aab1151fb6179563ad749ba

Thanks!

**Comment by cdiener** [comment] 2020-04-22 01:51
@thermokarst Looks good. `libcxx` was downgraded. Will add it back to our CI and see what happens. Thanks!
