### ISSUE TITLE
Installation of Guest Additions Not Automatic

### ISSUE THREAD

**Issue by Sirtaj-Singh** [qiime2/qiime2#256] opened 2017-05-06 03:07 UTC
I installed QIIME 2 today and was having trouble getting the guest additions installed, when I realized that I had to simply change the settings to add an optical drive to the QIIME 2 virtual machine. Providing an optical drive in the virtual machine as default may help fix this!

**Comment by thermokarst** [comment] 2017-05-06 15:13
Hi @Sirtaj-Singh, thanks for submitting this issue. You found a bug in the VirtualBox image --- the optical drive should be mounted by default, but it appears it isn't. I just tested this locally and confirmed what you are seeing. The previous releases of QIIME 2 (2017.2) mounted the optical drive, for what its worth. Anyway, I am closing this issue, because we have a [separate repo](https://github.com/qiime2/playbooks) for tracking our VM builds. You can find the new issue [here](https://github.com/qiime2/playbooks/issues/26). Thanks!

**Closed by thermokarst** 2017-05-06 15:13 UTC
