### ISSUE TITLE
Visualizers fail on OSX through async calls, due to matplotlib main thread limitations

### ISSUE THREAD

**Issue by jakereps** [qiime2/qiime2#73] opened 2016-07-05 20:35 UTC
Testing out the summarize visualizer from the feature-table plugin through qiime-studio revealed an issue where matplotlib does not work outside of the main thread on OSX. The Visualizer fails with the following traceback:

``` bash
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
Traceback (most recent call last):
  File "/Users/Develop/Developer/work/qiime-studio/qiime_studio/api/jobs.py", line 111, in callback
    results = future.result()
  File "/Users/Develop/anaconda/envs/qiime_studio/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/Users/Develop/anaconda/envs/qiime_studio/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

Found it was due to matplotlib through this SO exchange: http://stackoverflow.com/a/16303620
Sounds like this might need another workaround.

**Comment by ebolyen** [comment] 2016-07-05 20:37
Thanks @jakereps! I forgot about that issue, this is likely something we will  need to find a workaround for, for SciPy. @jairideout, @gregcaporaso are you familiar with this error?

**Comment by jairideout** [comment] 2016-07-05 21:50
I'm not familiar with this error. Does it still fail if you set the matplotlib backend to Agg (e.g., in your matplotlib config)? I wonder if it's just a GUI backend issue or more generally an issue with matplotlib. OS X ships with a matplotlib GUI backend by default.

**Comment by gregcaporaso** [comment] 2016-07-05 22:10
I'm also not familiar with this one.

**Comment by ebolyen** [comment] 2016-07-05 23:45
@gregcaporaso was able to summarize without running into this issue. So we'll need to figure out how to reproduce this...

**Comment by jairideout** [comment] 2016-07-06 00:12
What matplotlib backend does @jakereps have vs. @gregcaporaso? How was matplotlib installed on their machines?

**Comment by jakereps** [comment] 2016-07-06 02:26
Looks like my environment is using the default OSX backend, and was installed using the `conda create ... scikit-bio -c biocore` command to install matplotlib as a requirement.

```bash
(qiime_studio)Develop@myMac-2 ~ $ python -c 'import matplotlib as plt; print(plt.rcParams["backend"])'
MacOSX
```

**Comment by jairideout** [comment] 2016-07-06 15:26
Can you try changing your backend to Agg?

**Comment by gregcaporaso** [comment] 2016-07-06 16:14
My backend is agg, and was installed in the same way as @jakereps. I'm running mpl 1.5.1.

**Comment by jairideout** [comment] 2016-07-06 16:27
Thanks @jakereps and @gregcaporaso, sounds like a GUI backend (i.e. non-Agg) causes this problem. Not sure of the best way to fix this -- it'd be annoying for users to receive this error if their mpl config is set up wrong. Is there a way that QIIME 2 can always use an Agg backend regardless of user config?

**Comment by jakereps** [comment] 2016-07-06 16:32
Switching to Agg allowed it to finish, and work correctly after unzipping it and looking at the data. @jairideout, it is possible to temporarily override the parameters just using `plt.rcParams['backend'] = 'Agg'`, if that helps in anyway? Either in the Visualizer code itself, or within the plugin maybe? That's strange that we have different backends when installed the same way.

**Comment by jakereps** [comment] 2016-07-06 16:43
Or if this isn't an issue for qiime/q2cli, assuming async isn't called through the command line, the backend setting could just get toggled on the studio's server?

**Comment by ebolyen** [comment] 2016-07-06 16:49
`async` may be called interactively. It looks like there are experimental ways of changing it (forcing a reload): [`matplotlib.pyplot.switch_backend`](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.switch_backend) and [`matplotlib.use`](http://matplotlib.org/api/matplotlib_configuration_api.html#matplotlib.use)

**Comment by jairideout** [comment] 2017-03-08 20:28
Closing because the framework detects macOS mpl backend and raises an informative error.

**Closed by jairideout** 2017-03-08 20:28 UTC
